import './JS/fetchBooksAPI';
import './JS/mobile-menu';
import './JS/booksListGenerator';
import './JS/sidebar-categories';
import './JS/sidebar-foundations';
import './JS/renderModal';
import './JS/index-light-dark-theme';
import './JS/renderCtgrOnBtn';
import './JS/scroll-up';
// import './JS/firebase';
import './JS/preloader';